AMQP_URI: amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_HOST}:${RABBIT_PORT}/

WEB_SERVER_ADDRESS: '0.0.0.0:8007'
rpc_exchange: 'nameko-rpc'
max_workers: 10
parent_calls_tracked: 10

MONGO_URI: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_API}?authSource=admin
MONGO_DB_NAME: ${DB_API}
