[program:hoplias-classification]
command=/usr/local/bin/nameko run --config config.yml src.service
directory=/app/classification
user=root
autostart=true
autorestart=true
startretries=3
startsecs=10
stopwaitsecs=30
stdout_logfile=/var/log/supervisor/classification.log
stderr_logfile=/var/log/supervisor/classification_error.log
environment=DEBUG="1",LOGLEVEL="DEBUG",RABBIT_HOST="localhost",RABBIT_PORT="5672",RABBIT_MANAGEMENT_PORT="15672",GRAYLOG_HOST="localhost",GRAYLOG_PORT_UDP="12201",REDIS_URL="redis://localhost:6379"
priority=400

