[program:hoplias-gateway]
command=bash -c 'exec /usr/local/bin/gunicorn -w 4 -b 0.0.0.0:${GATEWAY_PORT:-8001} --timeout 120 "run:app" --access-logfile -'
directory=/app/gateway
user=root
autostart=true
autorestart=true
startretries=3
startsecs=10
stopwaitsecs=30
stdout_logfile=/var/log/supervisor/gateway.log
stderr_logfile=/var/log/supervisor/gateway_error.log
environment=DEBUG="1",LOGLEVEL="DEBUG",HOST_MQ="localhost",GRAYLOG_HOST="localhost",GRAYLOG_PORT_UDP="12201"
priority=100

