[program:hoplias-ideogram]
command=/usr/local/bin/nameko run --config config.yml src.service
directory=/app/ideogram
user=root
autostart=true
autorestart=true
startretries=3
startsecs=10
stopwaitsecs=30
stdout_logfile=/var/log/supervisor/ideogram.log
stderr_logfile=/var/log/supervisor/ideogram_error.log
environment=DEBUG="1",LOGLEVEL="DEBUG",RABBIT_HOST="localhost",RABBIT_PORT="5672",RABBIT_MANAGEMENT_PORT="15672",GRAYLOG_HOST="localhost",GRAYLOG_PORT_UDP="12201"
priority=500

