openapi: 3.0.0
info:
  title: Gateway API RPC Hoplias
  description: 'Api RPC to request in microsservices Hoplias.'
  version: 1.0.0-alpha
  termsOfService: 'http://localhost:8001'
  contact:
    email: rodrjuniorsantos@gmail.com
servers:
  - url: 'http://localhost:8001'
    description: 'Primary server, e.g. Main (Production) server'
components:
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: api-token
paths:
  /v1/api/segmentation/json:
    post:
      summary: Segmentation chromosomes for Hoplias.
      security:
        - APIKeyHeader: []
      tags:
        - Segmentation
      requestBody:
        description: Segmentation Functions
        required: true
        content:
          application/json:
            schema:
              type: object
              required: 
                - "src"
              properties: 
                src: 
                  type: "string"
      responses:
        '200':
          description: Segmentation successfully 
        '500':
          description: Gateway internal error
        '501':
          description: Service internal error
  /v1/api/classification/centromere:
    post:
      summary: Centromere chromosomes for Hoplias.
      security:
        - APIKeyHeader: []
      tags:
        - Classification
      requestBody:
        description: Centromere Function
        required: true
        content:
          application/json:
            schema:
              type: object
              required: 
                - "objects"
              properties: 
                objects: 
                  type: "array"
                  items: 
                    type: "object"
                    required: 
                      - "src"
                      - "points"
                    properties: 
                      angle: 
                        type: "number"
                      backgroundColor: 
                        type: "string"
                      cropX: 
                        type: "number"
                      cropY: 
                        type: "number"
                      crossOrigin: 
                        type: "string"
                      file: 
                        required: 
                          - "uid"
                        properties: 
                          uid: 
                            type: "string"
                        type: "object"
                      fill: 
                        type: "string"
                      fillRule: 
                        type: "string"
                      filters: 
                        type: "array"
                        items: 
                          type: "string"
                      flipX: 
                        type: "boolean"
                      flipY: 
                        type: "boolean"
                      globalCompositeOperation: 
                        type: "string"
                      height: 
                        type: "number"
                      id: 
                        type: "string"
                      layout: 
                        type: "string"
                      left: 
                        type: "number"
                      link: 
                        required: []
                        properties: {}
                        type: "object"
                      name: 
                        type: "string"
                      opacity: 
                        type: "number"
                      originX: 
                        type: "string"
                      originY: 
                        type: "string"
                      paintFirst: 
                        type: "string"
                      scaleX: 
                        type: "number"
                      scaleY: 
                        type: "number"
                      skewX: 
                        type: "number"
                      skewY: 
                        type: "number"
                      src: 
                        type: "string"
                      strokeDashOffset: 
                        type: "number"
                      strokeLineCap: 
                        type: "string"
                      strokeLineJoin: 
                        type: "string"
                      strokeMiterLimit: 
                        type: "number"
                      strokeWidth: 
                        type: "number"
                      tooltip: 
                        required: 
                          - "enabled"
                        properties: 
                          enabled: 
                            type: "boolean"
                        type: "object"
                      top: 
                        type: "number"
                      type: 
                        type: "string"
                      version: 
                        type: "string"
                      visible: 
                        type: "boolean"
                      width: 
                        type: "number"
                      workareaHeight: 
                        type: "number"
                      workareaWidth: 
                        type: "number"
                      animation: 
                        required: 
                          - "autoplay"
                          - "delay"
                          - "duration"
                          - "loop"
                          - "type"
                        properties: 
                          autoplay: 
                            type: "boolean"
                          delay: 
                            type: "number"
                          duration: 
                            type: "number"
                          loop: 
                            type: "boolean"
                          type: 
                            type: "string"
                        type: "object"
                      editable: 
                        type: "boolean"
                      points: 
                        type: "array"
                        items: 
                          type: "object"
                          properties: 
                            x: 
                              type: "number"
                            y: 
                              type: "number"
                      trigger: 
                        required: 
                          - "effect"
                          - "enabled"
                          - "script"
                          - "type"
                        properties: 
                          effect: 
                            type: "string"
                          enabled: 
                            type: "boolean"
                          script: 
                            type: "string"
                          type: 
                            type: "string"
                        type: "object"
                      userProperty: 
                        required: []
                        properties: {}
                        type: "object"
      responses:
        '200':
          description: Centromere search successfully 
        '500':
          description: Gateway internal error
        '501':
          description: Service internal error
  /v1/api/classification/classification:
    post:
      summary: Classification chromosomes for Hoplias.
      security:
        - APIKeyHeader: []
      tags:
        - Classification
      requestBody:
        description: Classification Function
        required: true
        content:
          application/json:
            schema:
              type: object
              required: 
                - "objects"
              properties: 
                objects: 
                  type: "array"
                  items: 
                    type: "object"
                    required: 
                      - "src"
                      - "points"
                    properties: 
                      angle: 
                        type: "number"
                      backgroundColor: 
                        type: "string"
                      cropX: 
                        type: "number"
                      cropY: 
                        type: "number"
                      crossOrigin: 
                        type: "string"
                      file: 
                        required: 
                          - "uid"
                        properties: 
                          uid: 
                            type: "string"
                        type: "object"
                      fill: 
                        type: "string"
                      fillRule: 
                        type: "string"
                      filters: 
                        type: "array"
                        items: 
                          type: "string"
                      flipX: 
                        type: "boolean"
                      flipY: 
                        type: "boolean"
                      globalCompositeOperation: 
                        type: "string"
                      height: 
                        type: "number"
                      id: 
                        type: "string"
                      layout: 
                        type: "string"
                      left: 
                        type: "number"
                      link: 
                        required: []
                        properties: {}
                        type: "object"
                      name: 
                        type: "string"
                      opacity: 
                        type: "number"
                      originX: 
                        type: "string"
                      originY: 
                        type: "string"
                      paintFirst: 
                        type: "string"
                      scaleX: 
                        type: "number"
                      scaleY: 
                        type: "number"
                      skewX: 
                        type: "number"
                      skewY: 
                        type: "number"
                      src: 
                        type: "string"
                      strokeDashOffset: 
                        type: "number"
                      strokeLineCap: 
                        type: "string"
                      strokeLineJoin: 
                        type: "string"
                      strokeMiterLimit: 
                        type: "number"
                      strokeWidth: 
                        type: "number"
                      tooltip: 
                        required: 
                          - "enabled"
                        properties: 
                          enabled: 
                            type: "boolean"
                        type: "object"
                      top: 
                        type: "number"
                      type: 
                        type: "string"
                      version: 
                        type: "string"
                      visible: 
                        type: "boolean"
                      width: 
                        type: "number"
                      workareaHeight: 
                        type: "number"
                      workareaWidth: 
                        type: "number"
                      animation: 
                        required: 
                          - "autoplay"
                          - "delay"
                          - "duration"
                          - "loop"
                          - "type"
                        properties: 
                          autoplay: 
                            type: "boolean"
                          delay: 
                            type: "number"
                          duration: 
                            type: "number"
                          loop: 
                            type: "boolean"
                          type: 
                            type: "string"
                        type: "object"
                      editable: 
                        type: "boolean"
                      points: 
                        type: "array"
                        items: 
                          type: "object"
                          properties: 
                            x: 
                              type: "number"
                            y: 
                              type: "number"
                      trigger: 
                        required: 
                          - "effect"
                          - "enabled"
                          - "script"
                          - "type"
                        properties: 
                          effect: 
                            type: "string"
                          enabled: 
                            type: "boolean"
                          script: 
                            type: "string"
                          type: 
                            type: "string"
                        type: "object"
                      userProperty: 
                        required: []
                        properties: {}
                        type: "object"
      responses:
        '200':
          description: Centromere search successfully 
        '500':
          description: Gateway internal error
        '501':
          description: Service internal error
tags:
  - name: Segmentation
    description: Segmentation metaphases  
  - name: Classification
    description: Classifying metaphases  
