from mongoengine import StringField, DateTimeField, DictField, IntField, ListField, BooleanField, EmbeddedDocument, EmbeddedDocumentListField, FloatField
from datetime import datetime, timezone
import uuid
from .base_model import BaseModel

class SegmentedAutomatic(EmbeddedDocument):
    id = StringField(required=True, default=lambda: str(uuid.uuid4()))
    left_contour = IntField(required=False)
    top_countour = IntField(required=False)
    contour =  ListField(required=False)
    id_chromosome = IntField(required=False)
    name = StringField(required=False)


class Chromosome(EmbeddedDocument):
    id = StringField(required=True, default=lambda: str(uuid.uuid4()))
    chromosomes_class = StringField(required=False)
    chromosomes_class_geodesic = StringField(required=False)
    chromosomes_class_point_to_point = StringField(required=False)
    chromosomes_class_simple = StringField(required=False)
    rb_geodesic = FloatField(required=False)
    rb_point = FloatField(required=False)
    rb_simple = FloatField(required=False)
    rb_mean = FloatField(required=False)
    size_geodesic = FloatField(required=False)
    size_point_to_point = FloatField(required=False)
    size_simple = FloatField(required=False)
    size_chrom = FloatField(required=False)
    upper_chromatide_size = FloatField(required=False)
    lower_chromatide_size = FloatField(required=False)
    centromere_start = FloatField(required=False)
    base_pairs = FloatField(required=False)
    centromere_bp = FloatField(required=False)
    checked = BooleanField(required=False)
    file_rgb_s3 = StringField(required=False)
    file_gray_s3 = StringField(required=False)
    file_rgb_gcs = StringField(required=False)
    file_gray_gcs = StringField(required=False)
    file_gray_local = StringField(required=False)
    file_rgb_local = StringField(required=False)
    file_rgb_drive = StringField(required=False)
    file_rgb_drive_id = StringField(required=False)
    file_gray_drive = StringField(required=False)
    file_gray_drive_id = StringField(required=False)
    obj_area = FloatField(required=False)
    dimension =  DictField(required=False)
    left_contour = IntField(required=False)
    top_countour = IntField(required=False)
    contour =  ListField(required=False)
    upper_measure_ruler = ListField(required=False)
    lower_measure_ruler = ListField(required=False)
    measure_width = IntField(required=False)
    measure_height =  IntField(required=False)
    centromere_coord = DictField(required=False)
    id_chromosome = IntField(required=False)
    left = IntField(required=False)
    top = IntField(required=False)
    name = StringField(required=False)
    canva = DictField(required=False)
    width = IntField(required=False)
    height = IntField(required=False)
    size = IntField(required=False)
    type_extension = IntField(required=False)
    manual = BooleanField(required=False)
    agent_who_identified_chromosome = StringField(required=False)
    agent_who_identified_centromere = StringField(required=False)
    agent_who_identified_rotation = StringField(required=False)
    rotation = DictField(required=False)
    times_recalculated = IntField(required=False)
    empty = BooleanField(required=False)
    batch_number = IntField(required=False)
    status_centromero = StringField(required=False)
    status_preclassification = StringField(required=False)


class KariotypeModel(BaseModel):
    meta = {
        'collection': 'kariotypes'
    }

    name = StringField(required=True, max_length=400)
    description = StringField(required=False, max_length=900)
    status = StringField(required=True, max_length=200)
    finished = BooleanField(required=False, default=False)
    chromosome_number = IntField(required=False)
    block_threshold = IntField(required=False)
    canva = DictField(required=False)
    chromosomes = EmbeddedDocumentListField(Chromosome, required=False)
    segmented_automatic = EmbeddedDocumentListField(SegmentedAutomatic, required=False)
    scheduled = DateTimeField(default=datetime.now(timezone.utc), required=False)
    categories = ListField(StringField(), required=False)
    field_of_view = IntField(required=False)
    image_resolution = IntField(required=False)
    times_reprocessed = IntField(required=False)
    file_s3 = StringField(required=False)
    folder_s3 = StringField(required=False)
    file_gcs = StringField(required=False)
    folder_gcs = StringField(required=False)
    file_local = StringField(required=False)
    folder_local = StringField(required=False)
    file_drive = StringField(required=False)
    file_drive_id = StringField(required=False)
    folder_drive = StringField(required=False)
    width = IntField(required=False)
    height = IntField(required=False)
    top = IntField(required=False)
    left = IntField(required=False)
    size = IntField(required=False)
    type_extension = IntField(required=False)
    user_id = StringField(required=False)
    folder_id = StringField(required=False)
    team_id = StringField(required=False)
    specie_id = StringField(required=False)
    address_id = StringField(required=False)
    specie_type = StringField(required=False)
    ordenation_type = StringField(required=False)
    batches_total = IntField(required=False)
