class SpecieTypeEnum:
    ANIMALS = 'ANIMALS'
    HUMANS = 'HUMANS'
    PLANTS = 'PLANTS'


class OrdenationTypeEnum:
    SIZE = 'SIZE'
    CLASS_SIZE = 'CLASS_SIZE'
    INDEX_CENTROMERIC = 'INDEX_CENTROMERIC'
    CLASS_INDEX_CENTROMERIC = 'CLASS_INDEX_CENTROMERIC'
