from enum import Enum

class RolesEnum(Enum):
  ADMINISTRATOR = 'ADMINISTRATOR'
  KARIOTYPE = 'KARIOTYPE'
  IDEOGRAM = 'IDEOGRAM'
  FOLDER = 'FOLDER'
  SPECIE = 'SPECIE'
  SETTINGS = 'SETTINGS'


class RulesEnum(Enum):
  EDIT_KARIOTYPE = 'EDIT_KARIOTYPE'
  ADD_KARIOTYPE = 'ADD_KARIOTYPE'
  VIEW_KARIOTYPE = 'VIEW_KARIOTYPE'
  EXPORT_KARIOTYPE = 'EXPORT_KARIOTYPE'
  REMOVE_KARIOTYPE = 'REMOVE_KARIOTYPE'

  EDIT_IDEOGRAM = 'EDIT_IDEOGRAM'
  ADD_IDEOGRAM = 'ADD_IDEOGRAM'
  VIEW_IDEOGRAM = 'VIEW_IDEOGRAM'
  EXPORT_IDEOGRAM = 'EXPORT_IDEOGRAM'
  REMOVE_IDEOGRAM = 'REMOVE_IDEOGRAM'

  EDIT_FOLDER = 'EDIT_FOLDER'
  ADD_FOLDER = 'ADD_FOLDER'
  VIEW_FOLDER = 'VIEW_FOLDER'
  EXPORT_FOLDER = 'EXPORT_FOLDER'
  REMOVE_FOLDER = 'REMOVE_FOLDER'

  EDIT_SPECIE = 'EDIT_SPECIE'
  ADD_SPECIE = 'ADD_SPECIE'
  VIEW_SPECIE = 'VIEW_SPECIE'
  EXPORT_SPECIE = 'EXPORT_SPECIE'
  REMOVE_SPECIE = 'REMOVE_SPECIE'
