class StatusKariotypeEnum:
    PENDING = 'PENDING'
    COMPLETED = 'COMPLETED'
    CANCELED = 'CANCELED'
    PLANNED = 'PLANNED'
    PAUSED = 'PAUSED'
    SEGMENTED_CHROMOSOMES = 'SEGMENTED_CHROMOSOMES'
    CENTROMERE_LOCALIZED = 'CENTROMERE_LOCALIZED'
    CLASSIFIED_CHROMOSOMES = 'CLASSIFIED_CHROMOSOMES'
    IDEOGRAM_BUILDED = 'IDEOGRAM_BUILDED'


class StatusChromosomeEnum:
    PENDING = 'PENDING'
    PROCESSING = 'PROCESSING'
    PROCESSED = 'PROCESSED'
    CANCELED = 'CANCELED'
    IN_QUEUE = 'IN_QUEUE'
